### ISSUE TITLE
Could you plz share your hdf5 file?

### ISSUE THREAD

**Issue by xeniazhanghx** [paulojamorim/panoramic_generator#1]
Hi, Paulo. I didn't find your contaction, so I write this issues. Forgive me.
I'm a student in China and working for my gaduation project. But I have some trouble in generating a hdf5 file with Invesalius. So I'm trying to write a hdf5 file by myself, could you please share me a hdf5 file in your project(panoramic_generator) to correct my code? Thank you very much. And this is my email: 20125277@bjtu.edu.cn

**Comment by paulojamorim** [comment]
Hi Xenia,

I uploaded a hdf5 file sample to: https://mega.nz/file/BTwGEARZ#WWe3fFLtEmU1YqWUsiggjiOCaIHQQ6gDErXQlBMkSS8

Best regards

**Comment by xeniazhanghx** [comment]
> Hi Xenia,
> 
> I uploaded a hdf5 file sample to: https://mega.nz/file/BTwGEARZ#WWe3fFLtEmU1YqWUsiggjiOCaIHQQ6gDErXQlBMkSS8
> 
> Best regards

Thank you. It's really useful.

**Comment by MinjaeLee583** [comment]
Hi, Paulo. Thank you very much for sharing your code. 
I'm a student studying in republic of Korea. 
Your code is working fine. But, sometimes only the upper part of the tooth line is imaged.
Is it possible to fully cover the head? Can you please let me know if possible?
Thank you.

**Comment by iskenderkahramanoglu** [comment]
Hi, thanks for this project.
I used the file that you shared in this project with default settings.
But result is not good as expected.
Can you help me, where is the problem?
![image](https://user-images.githubusercontent.com/57007275/219583805-d394471d-7bab-495f-909b-423730363463.png)

**Comment by paulojamorim** [comment]
Hi!

Would the problem be those white parts? I think this viewer is cutting some
gray values. Maybe it's not working with int16.

See the screenshot with .nii file on InVesalius. The second image is with
average projection applied on visualization.

[image: Screenshot from 2023-02-18 10-24-18.png]


[image: Screenshot from 2023-02-18 10-25-07.png]
