### ISSUE TITLE
I have a question.

### ISSUE THREAD

**Issue by ProjX0** [paulojamorim/panoramic_generator#2]
Hi, Paulo. firstly, thank you very much for sharing code.
I'm a student studying in republic of Korea.
Your code is working fine. But, sometimes only upper line of tooth is imaged. 
It is possible to fully cover the head? If possible, could you please let me know?
Thank you

**Comment by paulojamorim** [comment]
Hi Lee,

This code is experimental, in some cases it won't work well because it depends on the gray levels you have in the exam. Is the dental arch complete? If I understand you correctly, you want to see the entire skull panoramic but my code is only picking up part of it, right?

Regards,
Paulo Amorim

**Comment by ProjX0** [comment]
Hi, thank you for the reply.
Your research is very interesting and thank you for your good research.

yes, I want to see the entire skull panoramic
It is possible?

**Comment by paulojamorim** [comment]
Hi,

There are cases that are not possible because the algorithm uses the gray levels of the teeth as a base and they are not good or there are too many teeth missing.

**Comment by AUHS2001** [comment]
Hi Paulojamorim, Thanks for the code.
I am the undergraduate student and unable to run your code. it is generating errors, can you please guide me how to run it or share a demo video of running. It will be very helpful to me.

**Comment by AUHS2001** [comment]
paulojamorim thanks for the code.
could you please tell me the other methods for generating the hdf5 file from dicom images, because after generating hdf5 file from invesalius software the output is not like expected results.

**Comment by paulojamorim** [comment]
Hi @AUHS2001 

What's wrong with the output? 

Can you visualize the exam correctly in InVesalius before exporting to hdf5?

There's no other alternative.

**Comment by AUHS2001** [comment]
yes, the visualization of dicom images is correct.
![image](https://user-images.githubusercontent.com/62943513/219030094-d30d138b-b558-424e-87c0-bafc1133c7af.png)

**Comment by AUHS2001** [comment]
can you share any of your contact info so I can contact you directly and run the demo with you. ?
it will be very helpful for me.

**Comment by paulojamorim** [comment]
@AUHS2001 

My contact is paulojamorim@gmail.com

Record a screen video and send it (can upload on [wetransfer](https://wetransfer.com/))

**Comment by AUHS2001** [comment]
Sure @paulojamorim, I have mailed you. 
Please check, thank you.
